name: Deploy CDN

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "!.github/**"
      - "!.devops/**"
      - "!infra/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-version"
      - "!CODEOWNERS"
  
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod


jobs:
  compute_environment:
    name: Compute Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Determine Environment
        id: set_env
        run: |
          echo "environment=${{ inputs.env != null && inputs.env || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}" >> $GITHUB_OUTPUT
  
  release_and_deploy:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_cdn.yml@main
    name: "Release ${{ needs.compute_environment.outputs.environment }}"
    needs: compute_environment
    secrets: inherit
    with:
      environment: ${{ needs.compute_environment.outputs.environment }}
      file_environment: ${{ format('fe_{0}.env', needs.compute_environment.outputs.environment) }}
      storage_account_name: "checkoutsa"
      profile_name: checkout-cdn-profile
      endpoint_name: checkout-cdn-endpoint
      resource_group_name: checkout-fe-rg
      blob_container_name: "$web"
      base_path: auth

  promote_release:
    name: 'Promote prerelase release'
    if: ${{ inputs.env == 'prod' }}
    runs-on: ubuntu-20.04
    needs: [release_and_deploy]
    steps:
      - uses: pagopa/selfcare-commons/github-actions-template/promote-release@main
        with:
          github_path_token: ${{ secrets.GH_PAT_VARIABLES }}
          release_version: ${{ vars.CURRENT_UAT_VERSION }}
