name: Deploy CDN PNPG

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "!.github/**"
      - "!.devops/**"
      - "!infra/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-version"
      - "!CODEOWNERS"

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod

env:
  BUNDLE_NAME: bundle
  REACT_APP_ASSISTANCE_EMAIL: areariservata@assistenza.pagopa.it
  REACT_APP_OT_SRC: https://privacyportalde-cdn.onetrust.com/privacy-notice-scripts/otnotice-1.0.min.js
  REACT_APP_OT_TERMS_CONDITION_RESOURCE: https://privacyportalde-cdn.onetrust.com/77f17844-04c3-4969-a11d-462ee77acbe1/privacy-notices/6f92cced-3bd1-4859-9295-baecfc74c64a.json
  REACT_APP_OT_TOKEN: eyJjYWxsYmFja1VybCI6Imh0dHBzOi8vcHJpdmFjeXBvcnRhbC1kZS5vbmV0cnVzdC5jb20vcmVxdWVzdC92MS9wcml2YWN5Tm90aWNlcy9zdGF0cy92aWV3cyJ9
  REACT_APP_OT_TOS_RESOURCE: https://privacyportalde-cdn.onetrust.com/77f17844-04c3-4969-a11d-462ee77acbe1/privacy-notices/26403d01-dc46-4c89-be70-4894839cf639.json
  REACT_APP_ENABLE_ASSISTANCE: "true"
  REACT_APP_PAGOPA_HELP_EMAIL: "areariservata@assistenza.pagopa.it"

concurrency:
  group: ${{ github.workflow }}-cd
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build files
        env:
          INLINE_RUNTIME_CHUNK: "false"
          REACT_APP_ENV: ${{ (github.event_name == 'workflow_dispatch' && inputs.env == 'prod') && 'PROD' || (github.event_name == 'workflow_dispatch' && inputs.env == 'uat') && 'UAT' || startsWith(github.ref_name, 'releases/') && 'UAT' || 'DEV' }}
          REACT_APP_ENABLE_ASSISTANCE: ${{ env.REACT_APP_ENABLE_ASSISTANCE }}
          REACT_APP_PAGOPA_HELP_EMAIL: ${{ env.REACT_APP_PAGOPA_HELP_EMAIL }}
          REACT_APP_OT_SRC: ${{ env.REACT_APP_OT_SRC }}
          REACT_APP_OT_TOKEN: ${{ env.REACT_APP_OT_TOKEN }}
          REACT_APP_OT_TERMS_AND_CONDITION_RESOURCE: ${{ env.REACT_APP_OT_TERMS_CONDITION_RESOURCE }}
          REACT_APP_OT_TOS_RESOURCE: ${{ env.REACT_APP_OT_TOS_RESOURCE }}
        run: |
          ENVIRONMENT="${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}"
          ENV_ENDPOINT="https://raw.githubusercontent.com/pagopa/selfcare-commons/refs/heads/main/.github/workflows/env/fe_${ENVIRONMENT}_pnpg.env"
          export $(curl -s "$ENV_ENDPOINT" | xargs)
          yarn build
        shell: bash

      - name: Build info
        env:
          EXECUTION_ID: "${{ github.run_number }} - ${{ github.workflow }}(${{ github.run_id }})"
        run: printf "$EXECUTION_ID\n$(git name-rev --name-only FETCH_HEAD) $(git rev-parse HEAD)" > ${{ github.workspace }}/build/build.info
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: "${{ github.workspace }}/build"
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-22.04
    environment: "${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}-cd"
    env:
      ENVIRONMENT: ${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}
      ENV_SHORT: ${{ ((github.event_name == 'workflow_dispatch' && inputs.env == 'prod') || (github.event_name == 'push' && startsWith(github.ref_name, 'releases/'))) && 'p' || (github.event_name == 'workflow_dispatch' && inputs.env == 'uat') && 'u' || 'd' }}
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: ./${{ env.BUNDLE_NAME }}

      - name: Azure Login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        run: |
          az storage blob upload-batch \
            --account-name selc${{ env.ENV_SHORT }}weupnpgcheckoutst01 \
            --source "./${{ env.BUNDLE_NAME }}" \
            --destination '$web' \
            --destination-path 'auth' \
            --auth-mode login \
            --overwrite true

      - name: Purge Front Door endpoint
        run: |
          az afd endpoint purge \
            --resource-group selc-${{ env.ENV_SHORT }}-weu-pnpg-checkout-fe-rg \
            --profile-name selc-${{ env.ENV_SHORT }}-weu-pnpg-checkout-afd-01 \
            --endpoint-name selc-${{ env.ENV_SHORT }}-weu-pnpg-checkout-fde-01 \
            --content-paths "/auth" "/auth/*" "/"
